services:
  - type: web
    name: lostfinder-api
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_NAME
        value: LostFinder
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
